console.log('숫자자료')
console.log("가격 W 1,500")
console.log("총 결제 금액 W 0")
console.log("주문상품 : 1개")
console.log('문자열 자료')
console.log("커피류 (COFFEE)")
console.log("<>")
console.log("◀, ▶")
console.log('불리언 자료')
console.log("영수증 출력 예 , 아니오")
console.log("옵션 추가 ")
console.log("선택 / 취소")
console.log('배열 자료')
console.log("카테고리내용물 주스/에이드(커피)")
console.log("유료 옵션")
console.log("결제 방식")